In [1]:
import pandas as pd
import numpy as np

from sklearn.metrics.pairwise import cosine_similarity

In [2]:
initial = pd.read_csv('static/data/ratings_pivot_table.csv', index_col=0)
initial = initial.T # transpose
initial

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
'71 (2014),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
'Hellboy': The Seeds of Creation (2004),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Round Midnight (1986),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Salem's Lot (2004),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Til There Was You (1997),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
eXistenZ (1999),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,5.0,NaN,NaN,NaN,NaN,4.5,NaN,NaN
xXx (2002),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.5,NaN,2.0
xXx: State of the Union (2005),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.5
¡Three Amigos! (1986),4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
À nous la liberté (Freedom for Us) (1931),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
user_item = initial.fillna(0)
user_item

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
'71 (2014),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
'Hellboy': The Seeds of Creation (2004),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Round Midnight (1986),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Salem's Lot (2004),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Til There Was You (1997),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
eXistenZ (1999),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,5.0,0.0,0.0,0.0,0.0,4.5,0.0,0.0
xXx (2002),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.5,0.0,2.0
xXx: State of the Union (2005),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.5
¡Three Amigos! (1986),4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
À nous la liberté (Freedom for Us) (1931),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
user_similarity = cosine_similarity(user_item.T)
user_similarity = pd.DataFrame(user_similarity, columns = user_item.columns, index = user_item.columns).round(2)
user_similarity

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
userId,,,,,,,,,,,,,,,,,,,,,
1,1.00,0.03,0.06,0.19,0.13,0.13,0.16,0.14,0.06,0.02,...,0.08,0.16,0.22,0.07,0.15,0.16,0.27,0.29,0.09,0.15
2,0.03,1.00,0.00,0.00,0.02,0.03,0.03,0.03,0.00,0.07,...,0.20,0.02,0.01,0.00,0.00,0.03,0.01,0.05,0.03,0.10
3,0.06,0.00,1.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,...,0.01,0.00,0.02,0.00,0.01,0.01,0.02,0.02,0.00,0.03
4,0.19,0.00,0.00,1.00,0.13,0.09,0.12,0.06,0.01,0.03,...,0.09,0.13,0.31,0.05,0.08,0.20,0.13,0.15,0.03,0.11
5,0.13,0.02,0.01,0.13,1.00,0.30,0.11,0.43,0.00,0.03,...,0.07,0.42,0.11,0.26,0.15,0.11,0.15,0.14,0.26,0.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0.16,0.03,0.01,0.20,0.11,0.10,0.20,0.10,0.08,0.09,...,0.18,0.12,0.30,0.07,0.15,1.00,0.15,0.26,0.07,0.20
607,0.27,0.01,0.02,0.13,0.15,0.16,0.19,0.19,0.01,0.01,...,0.09,0.20,0.20,0.14,0.12,0.15,1.00,0.28,0.15,0.14
608,0.29,0.05,0.02,0.15,0.14,0.18,0.32,0.19,0.10,0.08,...,0.16,0.20,0.23,0.16,0.18,0.26,0.28,1.00,0.12,0.32
609,0.09,0.03,0.00,0.03,0.26,0.21,0.09,0.42,0.00,0.02,...,0.04,0.34,0.06,0.24,0.10,0.07,0.15,0.12,1.00,0.05
610,0.15,0.10,0.03,0.11,0.06,0.05,0.19,0.08,0.07,0.12,...,0.22,0.09,0.16,0.05,0.12,0.20,0.14,0.32,0.05,1.00

In [5]:
movies = initial.index
movies

Index([''71 (2014)', ''Hellboy': The Seeds of Creation (2004)',
       ''Round Midnight (1986)', ''Salem's Lot (2004)',
       ''Til There Was You (1997)', ''Tis the Season for Love (2015)',
       ''burbs, The (1989)', ''night Mother (1986)',
       '(500) Days of Summer (2009)', '*batteries not included (1987)',
       ...
       'Zulu (2013)', '[REC] (2007)', '[REC]² (2009)',
       '[REC]³ 3 Génesis (2012)',
       'anohana: The Flower We Saw That Day - The Movie (2013)',
       'eXistenZ (1999)', 'xXx (2002)', 'xXx: State of the Union (2005)',
       '¡Three Amigos! (1986)', 'À nous la liberté (Freedom for Us) (1931)'],
      dtype='object', length=9719)

In [27]:
new_user_query = {'Fight Club (1999)': 5}
df_new_user = pd.DataFrame(
        data=new_user_query,
        columns=movies,
        index = ['new_user']
)
df_new_user.T

                                          new_user
'71 (2014)                                     NaN
'Hellboy': The Seeds of Creation (2004)        NaN
'Round Midnight (1986)                         NaN
'Salem's Lot (2004)                            NaN
'Til There Was You (1997)                      NaN
...                                            ...
eXistenZ (1999)                                NaN
xXx (2002)                                     NaN
xXx: State of the Union (2005)                 NaN
¡Three Amigos! (1986)                          NaN
À nous la liberté (Freedom for Us) (1931)      NaN

[9719 rows x 1 columns]

In [7]:
user_item_with_new_user = user_item.join(df_new_user.T).fillna(0)
user_item_with_new_user

,1,2,3,4,5,6,7,8,9,10,...,602,603,604,605,606,607,608,609,610,new_user
'71 (2014),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0
'Hellboy': The Seeds of Creation (2004),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
'Round Midnight (1986),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
'Salem's Lot (2004),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
'Til There Was You (1997),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
eXistenZ (1999),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,5.0,0.0,0.0,0.0,0.0,4.5,0.0,0.0,0
xXx (2002),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.5,0.0,2.0,0
xXx: State of the Union (2005),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.5,0
¡Three Amigos! (1986),4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
À nous la liberté (Freedom for Us) (1931),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [8]:
user_similarity = cosine_similarity(user_item_with_new_user.T)
user_similarity = pd.DataFrame(user_similarity, columns = user_item_with_new_user.columns, index = user_item_with_new_user.columns).round(2)
user_similarity

,1,2,3,4,5,6,7,8,9,10,...,602,603,604,605,606,607,608,609,610,new_user
1,1.00,0.03,0.06,0.19,0.13,0.13,0.16,0.14,0.06,0.02,...,0.16,0.22,0.07,0.15,0.16,0.27,0.29,0.09,0.15,0.07
2,0.03,1.00,0.00,0.00,0.02,0.03,0.03,0.03,0.00,0.07,...,0.02,0.01,0.00,0.00,0.03,0.01,0.05,0.03,0.10,0.00
3,0.06,0.00,1.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,...,0.00,0.02,0.00,0.01,0.01,0.02,0.02,0.00,0.03,0.00
4,0.19,0.00,0.00,1.00,0.13,0.09,0.12,0.06,0.01,0.03,...,0.13,0.31,0.05,0.08,0.20,0.13,0.15,0.03,0.11,0.04
5,0.13,0.02,0.01,0.13,1.00,0.30,0.11,0.43,0.00,0.03,...,0.42,0.11,0.26,0.15,0.11,0.15,0.14,0.26,0.06,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
607,0.27,0.01,0.02,0.13,0.15,0.16,0.19,0.19,0.01,0.01,...,0.20,0.20,0.14,0.12,0.15,1.00,0.28,0.15,0.14,0.00
608,0.29,0.05,0.02,0.15,0.14,0.18,0.32,0.19,0.10,0.08,...,0.20,0.23,0.16,0.18,0.26,0.28,1.00,0.12,0.32,0.05
609,0.09,0.03,0.00,0.03,0.26,0.21,0.09,0.42,0.00,0.02,...,0.34,0.06,0.24,0.10,0.07,0.15,0.12,1.00,0.05,0.00
610,0.15,0.10,0.03,0.11,0.06,0.05,0.19,0.08,0.07,0.12,...,0.09,0.16,0.05,0.12,0.20,0.14,0.32,0.05,1.00,0.04
new_user,0.07,0.00,0.00,0.04,0.00,0.00,0.00,0.00,0.00,0.01,...,0.00,0.04,0.00,0.00,0.04,0.00,0.05,0.00,0.04,1.00

In [9]:
candidates = movies[df_new_user.T['new_user'].isna()]
candidates

Index([''71 (2014)', ''Hellboy': The Seeds of Creation (2004)',
       ''Round Midnight (1986)', ''Salem's Lot (2004)',
       ''Til There Was You (1997)', ''Tis the Season for Love (2015)',
       ''burbs, The (1989)', ''night Mother (1986)',
       '(500) Days of Summer (2009)', '*batteries not included (1987)',
       ...
       'Zulu (2013)', '[REC] (2007)', '[REC]² (2009)',
       '[REC]³ 3 Génesis (2012)',
       'anohana: The Flower We Saw That Day - The Movie (2013)',
       'eXistenZ (1999)', 'xXx (2002)', 'xXx: State of the Union (2005)',
       '¡Three Amigos! (1986)', 'À nous la liberté (Freedom for Us) (1931)'],
      dtype='object', length=9718)

In [10]:
neighbours = user_similarity['new_user'].sort_values(ascending=False).index[1:6]
neighbours

Index([157, 549, 180, 407, 258], dtype='object')

In [11]:
for movie in candidates:
    # extract users who have rated unseen movies
    current_movie_reviewers = initial.columns[~initial.loc[movie].isna()]
    # we want to create an intersection, so we save the users as a set-object
    current_movie_reviewers = set(current_movie_reviewers)

In [12]:
predictions = {}

for movie in candidates:
    #extract users who have rated unseen movies
    current_movie_reviewers = initial.columns[~initial.loc[movie].isna()]
    # we want to create an intersection, so we save the users as a set-object
    current_movie_reviewers = set(current_movie_reviewers)

    intersection = set(neighbours).intersection(current_movie_reviewers)
    if len(intersection) != 0:
        num = 0
        den = 0
        for neighbour in intersection:
            ratings = user_item_with_new_user[neighbour][movie] 
            sim_score = user_similarity['new_user'][neighbour]
            num = num + (ratings*sim_score)
            den = den + sim_score
        
        pred_ratings = num/den
        predictions[movie] = pred_ratings

predictions

{'Alice Through the Looking Glass (2016)': 1.0,
 'American Werewolf in London, An (1981)': 2.5,
 'Austin Powers: The Spy Who Shagged Me (1999)': 4.0,
 'Back to the Future (1985)': 4.0,
 'Beautiful Mind, A (2001)': 5.0,
 'Big Fish (2003)': 5.0,
 'Big Hero 6 (2014)': 5.0,
 'Blind Side, The  (2009)': 3.0,
 'Boiler Room (2000)': 4.0,
 'Bourne Ultimatum, The (2007)': 3.5,
 'Bowfinger (1999)': 3.0,
 'Braveheart (1995)': 3.0,
 'Caddyshack (1980)': 4.0,
 'Catch Me If You Can (2002)': 5.0,
 'Children of Men (2006)': 4.5,
 'Coraline (2009)': 4.5,
 'Dark City (1998)': 3.5,
 'Dark Crystal, The (1982)': 1.5,
 'Dark Knight, The (2008)': 4.471698113207547,
 'Deadpool (2016)': 5.0,
 'Departed, The (2006)': 5.0,
 'Die Hard (1988)': 3.5283018867924527,
 'District 9 (2009)': 4.5,
 'Dune (1984)': 3.5,
 'Evil Dead II (Dead by Dawn) (1987)': 4.0,
 'Fast Times at Ridgemont High (1982)': 3.0,
 'Galaxy Quest (1999)': 2.0,
 'Ghostbusters II (1989)': 4.0,
 'Glory (1989)': 3.5,
 'Gone Girl (2014)': 5.0,
 'Goodfellas (1990)': 4.5,
 'Grand Budapest Hotel, The (2014)': 3.5,
 'Green Mile, The (1999)': 5.0,
 'Guardians of the Galaxy 2 (2017)': 3.5,
 'How to Train Your Dragon (2010)': 4.239583333333334,
 'Inception (2010)': 5.0,
 'Indiana Jones and the Last Crusade (1989)': 3.4716981132075473,
 'Inspector Gadget (1999)': 2.0,
 'Iron Giant, The (1999)': 4.0,
 'Iron Man (2008)': 5.0,
 "It's a Wonderful Life (1946)": 3.0,
 'Jack Frost (1998)': 3.0,
 'Kingpin (1996)': 3.6363636363636362,
 'Lord of the Rings: The Fellowship of the Ring, The (2001)': 4.75,
 'Lord of the Rings: The Return of the King, The (2003)': 5.0,
 'Lord of the Rings: The Two Towers, The (2002)': 4.2075471698113205,
 'Léon: The Professional (a.k.a. The Professional) (Léon) (1994)': 4.056603773584906,
 'Man on the Moon (1999)': 3.0,
 'Matrix, The (1999)': 4.62871287128713,
 'Me, Myself & Irene (2000)': 5.0,
 'Memento (2000)': 5.0,
 'Minority Report (2002)': 5.0,
 'Monty Python and the Holy Grail (1975)': 4.0,
 'Mystery Men (1999)': 3.0,
 "One Flew Over the Cuckoo's Nest (1975)": 3.0,
 "Pan's Labyrinth (Laberinto del fauno, El) (2006)": 5.0,
 'Payback (1999)': 4.0,
 'Perfect Storm, The (2000)': 3.0,
 'Pirates of the Caribbean: The Curse of the Black Pearl (2003)': 4.0,
 'Princess Bride, The (1987)': 4.479166666666668,
 'Pursuit of Happyness, The (2006)': 3.0,
 'Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981)': 4.264150943396227,
 'Rain Man (1988)': 4.0,
 'Red Violin, The (Violon rouge, Le) (1998)': 3.0,
 'Road Trip (2000)': 3.0,
 'Runaway Bride (1999)': 2.0,
 'Saving Private Ryan (1998)': 4.528301886792454,
 "Schindler's List (1993)": 3.3333333333333335,
 'Shawshank Redemption, The (1994)': 4.450980392156864,
 'Sixth Sense, The (1999)': 4.5,
 'Specialist, The (1994)': 3.0,
 'Star Wars: Episode IV - A New Hope (1977)': 3.442307692307692,
 'Star Wars: Episode V - The Empire Strikes Back (1980)': 3.282051282051282,
 'Star Wars: Episode VI - Return of the Jedi (1983)': 2.0,
 'Star Wars: Episode VII - The Force Awakens (2015)': 0.5,
 'Stop! Or My Mom Will Shoot (1992)': 2.0,
 'Superman II (1980)': 3.5,
 'Terminator 2: Judgment Day (1991)': 3.0,
 'Terminator, The (1984)': 3.0,
 'Thor: Ragnarok (2017)': 3.0,
 'Up (2009)': 3.958333333333334,
 'WALL·E (2008)': 3.697916666666667,
 'Who Framed Roger Rabbit? (1988)': 4.0,
 'X-Men: Apocalypse (2016)': 5.0,
 'X-Men: First Class (2011)': 0.5}

In [25]:
[movie for movie, _ in sorted(predictions.items(), key=lambda item: item[1], reverse=True)][:10]

['Beautiful Mind, A (2001)',
 'Big Fish (2003)',
 'Big Hero 6 (2014)',
 'Catch Me If You Can (2002)',
 'Deadpool (2016)',
 'Departed, The (2006)',
 'Gone Girl (2014)',
 'Green Mile, The (1999)',
 'Inception (2010)',
 'Iron Man (2008)']